### ISSUE TITLE
Android system bars colors

### ISSUE THREAD

**Issue by simonesestito** [veetaw/quake#3]
The Android navigation bar and status bar should be tinted in a different way.

**Actual behavior**
![screenshot_20190122-072048](https://user-images.githubusercontent.com/24279760/51516092-5246db80-1e16-11e9-89df-020d64cd11ad.png)

**Expected behavior**
The status bar should be white as the top app bar, with black icons.
The navigation bar should be, since Oreo, white too as the bottom app bar, with black icons.
In older versions, maybe black as it is now or gray.

**Comment by veetaw** [comment]
implemented navbar color change, thanks for your issue.
